---
name: Hello World action

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Yo whats up world"
      - name: Display date
        run: |
          echo "The date is $(date)"
...