---
name: Hello World action

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Yo whats up world"

  display_date_job:
    runs-on: ubuntu-20.04
    steps:
        - name:  Display date
          run: |
            echo "The time is ${date}"
...