name: Render Deploy Action

on:
  push:
    branches:
      - render

jobs:
  build_app:
    runs-on: ubuntu-latest
    steps:
      - name: render-branch deploy
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}